name: github-pages
on: push
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - run: npm install
      - run: npm run compile
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v1

